#Create a twitter developer account to get below keys.
TWITTER_KEY = 'ENTER_API_KEY'
TWITTER_SECRET = 'ENTER_SECRET_KEY'
TWITTER_APP_KEY = 'ENTER_ACCESS_KEY'
TWITTER_APP_SECRET = 'ENTER_ACCEESS_SECRET'
